### ISSUE TITLE
实验设置

### ISSUE THREAD

**Issue by orangeslx** [mengzaiqiao/CAN#12]
您好，我想问您两个问题，希望得到您的回复
1.我想问的是链接预测实验和属性推断实验代码在一块，这俩实验是否同时进行？如果是的话。两个实验都会使用全部的特征进行训练
2.如果是链接预测实验和属性推断实验同时进行的话，是将所有的边划分成5%验证数据集和10%测试数据集以及将特征划分成5%验证数据集和10%测试数据集下得到节点嵌入数据，然后进行分类实验吗？

**Comment by mengzaiqiao** [comment]
抱歉，我以为我在上一个issue已经回答你这个问题了。链接预测实验在做embedding训练的到时候已经做了划分，所以在test set结果可以直接输出。其他两个任务，也是基于这个得到的embedding进行的。比如，节点分类，还是要划分train validataion 和 test sets，然后用这些得到的embedding进行实验。
