### ISSUE TITLE
嵌入文件

### ISSUE THREAD

**Issue by orangeslx** [mengzaiqiao/CAN#13]
您好，我有一个疑问。对于同一个数据集来说，运行一次train.py就会产生一个嵌入文件，请问当再次运行train.py产生的嵌入文件会覆盖上次运行的嵌入文件对吗？

**Comment by mengzaiqiao** [comment]
对。你可修改这里更改embedding保存。
https://github.com/mengzaiqiao/CAN/blob/master/train.py#L191-L192

**Comment by orangeslx** [comment]
谢谢你，原来我一直在重新运行之前会上一次的嵌入文件删掉，看来不需要这么麻烦了
