### ISSUE TITLE
循环设置

### ISSUE THREAD

**Issue by orangeslx** [mengzaiqiao/CAN#14]
您好，不好意思又来打扰你，我设置循环重复运行10次，在循环中使用  tf.reset_default_graph()初始化图之后进行数据加载和节点划分操作，请问这样会对你代码效果有影响吗

**Comment by mengzaiqiao** [comment]
这个应该没什么问题的。

**Comment by orangeslx** [comment]
真的感谢您，您对我的帮助很大，希望你的每一天都很愉快~
