### ISSUE TITLE
链接预测实验

### ISSUE THREAD

**Issue by orangeslx** [mengzaiqiao/CAN#15]
您好，您的工作非常出色，我想问链接预测实验中get_roc_score（）函数中定义了  
 def sigmoid(x):
   x = np.clip(x, -500, 500）
   return 1.0 / (1 + np.exp(-x))
，但是有些基线没有做 x = np.clip(x, -500, 500）处理，我想问您做对比实验时，是否设置所有基线方法中调用get_roc_score（）中sigmoid函数时，做x = np.clip(x, -500, 500）处理？还是说做与不做 x = np.clip(x, -500, 500）对效果没有影响，期待您的回复！

**Comment by mengzaiqiao** [comment]
你好。不做clip会对某一些数据集产生很大影响。应用clip可以确保大部分数据集能获得理想效果

**Comment by orangeslx** [comment]
那您在做对比实验时，使对比基线进行clip处理吗？

**Comment by orangeslx** [comment]
你好，我运行CAN源代码之后，发现分类结果与您论文中有所差距，想问您论文中的分类结果是训练比例是20%的情况下的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mengzaiqiao/CAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月3日(星期五) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mengzaiqiao/CAN] 链接预测实验 (#15)





 
Closed #15.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
