### ISSUE TITLE
Where is the embedding file?

### ISSUE THREAD

**Issue by Tomposon** [mengzaiqiao/CAN#2]
There are the 4 embedding files in the "result" folder, but is it the final embeddings of the node?  Is the node embedding for node classification  model.z_u ?

**Comment by mengzaiqiao** [comment]
The 4 embedding files in the "result" folder are the final embeddings of nodes and attributes, where *u_mu.* and *u_sig.* are model.z_u_mean and model.z_u_log_std respectively in our model. model.z_u is the generative embeddings with noise, while z_u_mean is our output embeddings.

**Comment by Tomposon** [comment]
I usd the z_u_mean as node embedding to do the node classification for cora.But the f1 score was very low.
@mengzaiqiao

**Comment by mengzaiqiao** [comment]
@Tomposon  How low it was in your experiment? What's your node classification algorithm? Have you  Have you tried them in other datasets? How many iteration have you made in your embedding training?

**Comment by Tomposon** [comment]
It's about 0.3. I use the linear SVM as a classification algorithm. I have only tried the cora dataset. The iteration follows your original implementation, it iterates for 200 times. @mengzaiqiao

**Comment by Tomposon** [comment]
How the embeddings in u_mu file correspond the node id? Does it follow the node id?  @mengzaiqiao

**Comment by mengzaiqiao** [comment]
@Tomposon Maybe it is the problem on your classification algorithm. We have already provided a classification algorithm in our code. Why not try it? The embedding in the result file is numbered in a normal order, i.e. the first row is the embedding of nodeID 0.

**Comment by Tomposon** [comment]
I will try it.

**Comment by Tomposon** [comment]
I have addressed it.Thank you! @mengzaiqiao
