### ISSUE TITLE
Something about the experiment.

### ISSUE THREAD

**Issue by Tomposon** [mengzaiqiao/CAN#3]
Do you train 32-dimensional embeddings with every algorithm? I tried to train 32-dimensional embeddings for BlogCatalog dataset with AANE algorithm. Then I used the embeddings to do node classification. But I can't get the performance mentioned in your paper. Thank for your attention. @mengzaiqiao

**Comment by mengzaiqiao** [comment]
Normally it is 32. I think you should try it in different number of iterations, as it can influence the classification performance. If you still cannot get our performance, please report your settings and result to me, then I'll track that for you.
------------------------------------------------------

Best Regards,

Zaiqiao Meng


On Mar 28, 2019, at 12:46 PM, Mr.Chen <notifications@github.com> wrote:
Do you train 32-dimensional embeddings with every algorithm? I tried to train 32-dimensional embeddings for BlogCatalog dataset with AANE algorithm. Then I used the embeddings to do node classification. But I can't get the performance mentioned in your paper. Thank for your attention. @mengzaiqiao
