### ISSUE TITLE
computational complexity

### ISSUE THREAD

**Issue by snash4** [mengzaiqiao/CAN#4]
Hi, 
 I am interested in knowing the computational complexity of your model. It is not given in the paper. 
Can you please tell me the overall computational complexity of your model.

**Comment by mengzaiqiao** [comment]
Hi,
The computational cost of our model is largely dependent on the part of GCN. Other parts of our model cost less than GCN, so in general, you can just refer to the computational complexity of GCN.

**Comment by snash4** [comment]
Hi, 
Thanks for the answer.
