### ISSUE TITLE
please share the code about user profiling

### ISSUE THREAD

**Issue by xdlequ** [mengzaiqiao/CAN#6]
Dear author, thank you very much for your outstanding contribution in this field. Your article has given me great inspiration.I hope you can open source the code of user profiling in the paper. My email is lqu@stu.xidian.edu.cn

**Comment by mengzaiqiao** [comment]
Hi, 
The implementation of user profiling is pretty easy. We just calculate the cosine similarities between authors and conferences according to their embeddings, which we directly use the function from scikit-learn. If you still have any questions, please let me know.
