### ISSUE TITLE
实验结果

### ISSUE THREAD

**Issue by orangeslx** [mengzaiqiao/CAN#9]
Hello, your paper is excellent, and the effect of link prediction is amazing. I would like to ask you 2 questions:
1.Will the final result of your link prediction be the average after running train.py 10 times?
2.In cora data set, AGAE_cora_a_mu.emb.npy is the embedding file of the node. Is the result of classification in the paper the result of getting a node embedding file for 10 times? Or after getting a node embedded file, do a classification experiment?

**Comment by mengzaiqiao** [comment]
Hi, thanks for your interest in our work. For your questions:
1. The reported result in our paper is the average result of 10 times runs. Each run has its respective result output, you need to do the average by yourself.
2. The classification result is the average of classification result over 10 different trained embeddings.

Hope this helps.

**Comment by orangeslx** [comment]
Thank you for your reply and answer most of my doubts. The input of your classification experiment is AGAE_cora_n_mu.emb.npy (cora as an example).
1. What does the AGAE_cora_n_mu.emb.npy file store the embedding of all nodes?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mengzaiqiao/CAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月1日(星期天) 晚上8:18
收件人:&nbsp;"mengzaiqiao/CAN"<CAN@noreply.github.com&gt;;
抄送:&nbsp;"兜里有颗糖"<1831756224@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mengzaiqiao/CAN] 实验结果 (#9)





 
Hi, thanks for your interest in our work. For your questions:
  
The reported result in our paper is the average result of 10 times runs. Each run has its respective result output, you need to do the average by yourself.
 
The classification result is the average of classification result over 10 different trained embeddings.
  
Hope this helps.

**Comment by mengzaiqiao** [comment]
AGAE_cora_n_mu.emb.npy is the nodes embeddings of one single run for the Cora dataset.

**Comment by orangeslx** [comment]
Sincerely thank you for your answers, because I have done many experiments, I want to confirm again:
1. After performing a link prediction experiment, get a node embedding, and then perform a classification experiment? Then perform the link prediction experiment to get the node embedding file, and then perform the classification task.........So the link prediction-node embedding file-classification experiment is performed 10 times? It’s not about 10 classification experiments for a node embedding, right? Thank you for your answer, it is very important to me!

（中文解释：真诚地感谢您的解答，因为我进行了多次试验，我想再次确认一下：
1.进行一次链接预测实验之后，得到一次节点嵌入，然后进行一次分类实验是吗？然后在进行链接预测实验，得到节点嵌入文件，然后进行分类任务.........这样链接预测-节点嵌入文件-分类实验进行10次？并不是对于一个节点嵌入进行10次分类实验对吗？谢谢您的解答，对我很重要！）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mengzaiqiao/CAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月1日(星期天) 晚上8:33
收件人:&nbsp;"mengzaiqiao/CAN"<CAN@noreply.github.com&gt;;
抄送:&nbsp;"兜里有颗糖"<1831756224@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mengzaiqiao/CAN] 实验结果 (#9)





 
AGAE_cora_n_mu.emb.npy is the nodes embeddings of one single run for the Cora dataset.

**Comment by mengzaiqiao** [comment]
对，每一个实验结果都是重新进行train embeddings。你可以直接先train10次不同的embedding，然后再用这10个不同的 embedding进行链路预测或者分类。需要用不同的random seeds，要不然结果是一样的，因为embedding training和task training 都具有随机性。在embedding部分随机性在于test edges masking和reparameterization trick。task部分随机性在于train/test split。希望对你有帮助。

**Comment by orangeslx** [comment]
我明白了，再次谢谢您的解答，您的代码中给出了得到一次邻接预测结果的同时，也会得到相应数据集的节点的嵌入，我进行了10次链接预测实验，将每次得到的节点嵌入进行都会进行一次分类实验，这样就可以同时记录分类和连接预测的结果，这样操作也可以吗？谢谢您百忙之中为我解答。希望您前途似锦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mengzaiqiao/CAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月1日(星期天) 晚上9:05
收件人:&nbsp;"mengzaiqiao/CAN"<CAN@noreply.github.com&gt;;
抄送:&nbsp;"兜里有颗糖"<1831756224@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mengzaiqiao/CAN] 实验结果 (#9)





 
对，每一个实验结果都是重新进行train embeddings。你可以直接先train10次不同的embedding，然后再用这10个不同的 embedding进行链路预测或者分类。需要用不同的random seeds，要不然结果是一样的，因为embedding training和task training 都具有随机性。在embedding部分随机性在于test edges masking和reparameterization trick。task部分随机性在于train/test split。希望对你有帮助。

**Comment by mengzaiqiao** [comment]
这样操作没问题。不客气。
